blueprint:
  name: Homebox Asset Location Change
  description: Trigger actions when a Homebox asset changes location
  domain: automation
  input:
    asset_entity:
      name: Asset Entity
      description: The Homebox asset entity to monitor
      selector:
        entity:
          domain: sensor
          integration: homebox
    target_location:
      name: Target Location
      description: The location name that will trigger this automation
      selector:
        text:
    actions:
      name: Actions
      description: The actions to perform when the asset moves to the target location
      selector:
        action:

trigger:
  - platform: state
    entity_id: !input asset_entity

condition:
  - condition: template
    value_template: "{{ trigger.to_state.state == input.target_location }}"

action:
  - choose:
      - conditions:
          - condition: template
            value_template: "{{ trigger.from_state.state != input.target_location }}"
        sequence: !input actions
